# Generated by Django 3.2.5 on 2022-08-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book1',
        ),
    ]
