# Generated by Django 3.2.5 on 2022-09-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_book_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
    ]
